version: '9.4'

services:

  maya-energy-dashboard-api:
    image: maya-energy-dashboard-api
    container_name: maya-energy-dashboard-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8888:8080
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
